name: base-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.49.0
  - jupyter-resource-usage=1.1.0
  - jupyterhub==5.3.0
  - jupyterlab==4.4.3
  - jupyter-archive==3.4.0
  - jupyter_server==2.16.0
  - jupyterlab-git==0.51.2
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.4.3
  - python==3.12.*
  - pip==25.1.1

  # vscode
  - code-server==4.101.1
  - jupyter-vscode-proxy==0.6
  - jupyter-server-proxy==4.4.0

  # data science
  - datascience==0.17.6
  - matplotlib==3.10.3
  - numpy==2.3.0
  - geopandas==1.1.0
  - openpyxl==3.1.5
  - pandas==2.3.0
  - plotly==6.1.2
  - scikit-learn==1.7.0
  - scipy==1.15.2
  - seaborn==0.13.2
  - statsmodels==0.14.4

  # pip installed packages, conda is preferred
  - pip:
    # https://github.com/jupyter-java
    - jbang==0.7.0
    # r2d installs jupyter-shiny-proxy, but in the base python env, not in the updated one
    - jupysql==0.10.15
    - nbconvert[webpdf]==7.16.4
    - otter-grader==6.1.3
